var f;f||=typeof Module != 'undefined' ? Module : {};var aa=Object.assign({},f),ba=[],ca="./this.program",da=(a,b)=>{throw b;},h="";"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src);h=h.startsWith("blob:")?"":h.substr(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1);var ea=f.print||console.log.bind(console),k=f.printErr||console.error.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);
f.quit&&(da=f.quit);var fa;f.wasmBinary&&(fa=f.wasmBinary);var ha,n=!1,ia,ja,q,ka,t,v,z,B,la=[],ma=[],na=[],oa=[];function pa(){var a=f.preRun.shift();la.unshift(a)}var C=0,qa=null,ra=null;function sa(a){f.onAbort?.(a);a="Aborted("+a+")";k(a);n=!0;ia=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta=a=>a.startsWith("data:application/octet-stream;base64,"),ua;
function wa(a){if(a==ua&&fa)return new Uint8Array(fa);throw"both async and sync fetching of the wasm failed";}function xa(a){return fa||"function"!=typeof fetch?Promise.resolve().then(()=>wa(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>wa(a))}function ya(a,b,c){return xa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{k(`failed to asynchronously prepare wasm: ${d}`);sa(d)})}
function za(a,b){var c=ua;fa||"function"!=typeof WebAssembly.instantiateStreaming||ta(c)||"function"!=typeof fetch?ya(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k(`wasm streaming compile failed: ${e}`);k("falling back to ArrayBuffer instantiation");return ya(c,a,b)}))}function Aa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ba=a=>{for(;0<a.length;)a.shift()(f)},Ca=f.noExitRuntime||!0,Da=a=>0===a%4&&(0!==a%100||0===a%400),Ea=[0,31,60,91,121,152,182,213,244,274,305,335],Fa=[0,31,59,90,120,151,181,212,243,273,304,334],D=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var p=a.charCodeAt(++g);l=65536+((l&1023)<<10)|p&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|
l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e},Ga=0,Ha=[];function Ia(){if(navigator.userActivation?navigator.userActivation.isActive:Ga&&Ja.te)for(var a=0;a<Ha.length;++a){var b=Ha[a];Ha.splice(a,1);--a;b.zf(...b.Ve)}}var E=[];function Ka(a){var b=E[a];b.target.removeEventListener(b.ad,b.Nd,b.Jd);E.splice(a,1)}
function La(a){if(!a.target)return-4;if(a.Md)a.Nd=function(c){++Ga;Ja=a;Ia();a.Qd(c);Ia();--Ga},a.target.addEventListener(a.ad,a.Nd,a.Jd),E.push(a);else for(var b=0;b<E.length;++b)E[b].target==a.target&&E[b].ad==a.ad&&Ka(b--);return 0}
var Ja,Ma,Na,Oa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Oa)return Oa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Pa=[0,document,window],Qa=a=>{a=2<a?a?F(q,a):"":a;return Pa[a]||document.querySelector(a)},Ra=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,l)=>b.drawElementsInstancedANGLE(c,d,e,g,l))},Sa=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Ta=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Ua=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Va=1,Wa=[],G=[],Xa=[],H=[],I=[],J=[],Ya=[],Za=[],K=[],$a={},ab=4,bb=a=>{for(var b=Va++,c=a.length;c<b;c++)a[c]=null;return b},cb=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=L[c](),l=g&&bb(d);g?(g.name=l,d[l]=g):M||=1282;t[b+4*e>>2]=l}},eb=(a,b)=>{a.dd||(a.dd=a.getContext,a.getContext=function(d,e){e=a.dd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?db(c,b):0},db=(a,b)=>{var c=bb(Za),
d={handle:c,attributes:b,version:b.De,xd:a};a.canvas&&(a.canvas.Te=d);Za[c]=d;("undefined"==typeof b.Ae||b.Ae)&&fb(d);return c},fb=a=>{a||=gb;if(!a.Ce){a.Ce=!0;var b=a.xd;Ra(b);Sa(b);Ta(b);b.Sc=b.getExtension("EXT_disjoint_timer_query");b.kf=b.getExtension("WEBGL_multi_draw");Ua(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},hb={},M,gb,ib=[],jb=(a,b,c,d,e,g,l,p)=>{b=G[b];if(a=L[a](b,c))d=p&&D(a.name,q,p,d),e&&(t[e>>2]=d),g&&(t[g>>2]=a.size),l&&(t[l>>2]=a.type)},
kb=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(M||=1280);return;case 36345:d=0;break;case 34466:var e=L.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=L.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":M||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:M||=1280;return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+4*a>>2]=e[a];break;case 2:z[b+4*a>>2]=e[a];break;case 4:ja[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){M||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:M||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=
d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;case 0:t[b>>2]=d;break;case 2:z[b>>2]=d;break;case 4:ja[b]=d?1:0}}else M||=1281},lb=(a,b,c)=>{if(c){a=L.Sc.getQueryObjectEXT(K[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d;v[c+4>>2]=(d-v[c>>2])/4294967296}else M||=1281},mb=(a,b,c)=>{if(c){a=L.Sc.getQueryObjectEXT(K[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d}else M||=1281},nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=
4,++c):b+=3}return b},ob=a=>{var b=nb(a)+1,c=N(b);c&&D(a,q,c,b);return c};function pb(){var a=Ua(L);return a=a.concat(a.map(b=>"GL_"+b))}
var qb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),rb=a=>{var b=a.cd,c=a.me,d;if(!b)for(a.cd=b={},a.le={},d=0;d<L.getProgramParameter(a,35718);++d){var e=L.getActiveUniform(a,d);var g=e.name;e=e.size;var l=qb(g);l=0<l?g.slice(0,l):g;var p=a.Id;a.Id+=e;c[l]=[e,p];for(g=0;g<e;++g)b[p]=g,a.le[p++]=l}},O=a=>{var b=L.we;if(b){var c=b.cd[a];"number"==typeof c&&(b.cd[a]=c=L.getUniformLocation(b,b.le[a]+(0<c?`[${c}]`:"")));return c}M||=1282},sb=(a,b,c,d)=>{if(c)if(a=G[a],rb(a),a=L.getUniform(a,O(b)),"number"==
typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:z[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b]}else M||=1281},tb=(a,b,c,d)=>{if(c)if(a=L.getVertexAttrib(a,b),34975==b)t[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:z[c>>2]=a;break;case 5:t[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b];break;case 5:t[c+
4*b>>2]=Math.fround(a[b])}else M||=1281},ub=(a,b,c,d,e)=>{a-=5120;a=1==a?q:4==a?t:6==a?z:5==a||28922==a?v:ka;var g=ab;b=d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+g-1&-g);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},P=[],vb=[],wb=a=>{a instanceof Aa||"unwind"==a||da(1,a)},xb=a=>{ia=a;Ca||(f.onExit?.(a),n=!0);da(a,new Aa(a))},yb=a=>{ia=a;xb(a)},zb=!1,Q=null,Ab=0,Bb=null,Cb=0,Db=0,Eb=0,Fb=0,Gb=[],Hb={},Ib,Jb,Kb,R=!1,Lb=
!1,Mb=[];
function Nb(){function a(){Lb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}if(!Ob){Ob=!0;var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",c=>{!Lb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Pb(a,b,c,d){if(b&&f.Xc&&a==f.canvas)return f.Xc;var e;if(b){var g={antialias:!1,alpha:!1,De:1};if(d)for(var l in d)g[l]=d[l];if("undefined"!=typeof hb&&(e=eb(a,g)))var p=Za[e].xd}else p=a.getContext("2d");if(!p)return null;c&&(f.Xc=p,b&&(gb=Za[e],f.Xc=L=gb?.xd),f.Cf=b,Mb.forEach(r=>r()),Nb());return p}var Qb=!1,S=void 0,U=void 0;
function Rb(a,b){function c(){R=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Sb,S&&d.requestPointerLock(),R=!0,U?Tb():V(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),U?Ub():V(d));f.onFullScreen?.(R);f.onFullscreen?.(R)}S=a;U=b;"undefined"==typeof S&&(S=!0);"undefined"==typeof U&&(U=!1);var d=f.canvas;Qb||(Qb=!0,document.addEventListener("fullscreenchange",
c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):
null);e.requestFullscreen()}function Sb(){if(!R)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Vb=0;function Wb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Vb)Vb=b+1E3/60;else for(;b+2>=Vb;)Vb+=1E3/60;setTimeout(a,Math.max(Vb-b,0))}}var Xb=0,Yb=0,Zb=0,$b=0;
function ac(a,b){var c=f.canvas.getBoundingClientRect(),d=f.canvas.height;a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;a*=f.canvas.width/c.width;b*=d/c.height;return{x:a,y:b}}function bc(a,b){const {x:c,y:d}=ac(a,b);Zb=c-Xb;$b=d-Yb;Xb=c;Yb=d}
function cc(a){Lb?("mousemove"!=a.type&&"mozMovementX"in a?Zb=$b=0:(Zb=a.movementX||a.mozMovementX||a.webkitMovementX||0,$b=a.movementY||a.mozMovementY||a.webkitMovementY||0),Xb+=Zb,Yb+=$b):"touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type?(a=a.Bf,void 0!==a&&ac(a.pageX,a.pageY)):bc(a.pageX,a.pageY)}var dc=[];function fc(){var a=f.canvas;dc.forEach(b=>b(a.width,a.height))}function gc(a,b,c){V(f.canvas,a,b);c||fc()}
function Tb(){"undefined"!=typeof SDL&&(t[SDL.screen>>2]=v[SDL.screen>>2]|8388608);V(f.canvas);fc()}function Ub(){"undefined"!=typeof SDL&&(t[SDL.screen>>2]=v[SDL.screen>>2]&-8388609);V(f.canvas);fc()}
function V(a,b,c){b&&c?(a.Ld=b,a.Bd=c):(b=a.Ld,c=a.Bd);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}U?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Ob,hc,jc=(a,b)=>{Db=a;Eb=b;if(Bb)if(zb||=!0,0==a)Q=function(){var d=Math.max(0,Jb+b-ic())|0;setTimeout(Kb,d)};else if(1==a)Q=function(){Wb(Kb)};else if(2==a){if("undefined"==typeof hc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);hc=function(d){c.push(d);postMessage("setimmediate","*")}}else hc=setImmediate;Q=function(){hc(Kb)}}},ic;ic=()=>performance.now();
var kc=(a,b,c,d,e)=>{Bb=a;Cb=d;var g=Ab;zb=!1;Kb=function(){if(!n)if(0<Gb.length){var l=Gb.shift();l.bf(l.Ue);if(Ib){var p=Ib,r=0==p%1?p-1:Math.floor(p);Ib=l.Ye?r:(8*p+(r+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",p=Ib,r=Hb.$e,p?p<r?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));g<Ab||setTimeout(Kb,0)}else if(!(g<Ab))if(Fb=Fb+1|0,1==Db&&1<Eb&&0!=Fb%Eb)Q();else{0==Db&&(Jb=ic());if(!(n||f.preMainLoop&&!1===f.preMainLoop())){if(!n)try{if(a(),
!Ca)try{ia=l=ia,xb(l)}catch(w){wb(w)}}catch(w){wb(w)}f.postMainLoop?.()}g<Ab||("object"==typeof SDL&&SDL.audio?.lf?.(),Q())}};e||(b&&0<b?jc(0,1E3/b):jc(1,1),Q());if(c)throw"unwind";},lc=[],mc,W=a=>{var b=lc[a];b||(a>=lc.length&&(lc.length=a+1),lc[a]=b=mc.get(a));return b},nc=(a,b,c,d)=>{Ma||=N(36);a=Qa(a);return La({target:a,ad:"resize",Md:d,Qd:(e=event)=>{if(e.target==a){var g=document.body;if(g){var l=Ma;t[l>>2]=0;t[l+4>>2]=g.clientWidth;t[l+8>>2]=g.clientHeight;t[l+12>>2]=innerWidth;t[l+16>>2]=
innerHeight;t[l+20>>2]=outerWidth;t[l+24>>2]=outerHeight;t[l+28>>2]=pageXOffset|0;t[l+32>>2]=pageYOffset|0;W(d)(10,l,b)&&e.preventDefault()}}},Jd:c})},oc=(a,b,c,d,e,g)=>{Na||=N(1696);a=Qa(a);return La({target:a,te:"touchstart"==g||"touchend"==g,ad:g,Md:d,Qd:l=>{for(var p,r={},w=l.touches,u=0;u<w.length;++u)p=w[u],p.Td=p.ie=0,r[p.identifier]=p;for(u=0;u<l.changedTouches.length;++u)p=l.changedTouches[u],p.Td=1,r[p.identifier]=p;for(u=0;u<l.targetTouches.length;++u)r[l.targetTouches[u].identifier].ie=
1;w=Na;B[w>>3]=l.timeStamp;var A=w>>2;t[A+3]=l.ctrlKey;t[A+4]=l.shiftKey;t[A+5]=l.altKey;t[A+6]=l.metaKey;A+=7;var va=0>Pa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},m=0;for(u in r)if(p=r[u],t[A]=p.identifier,t[A+1]=p.screenX,t[A+2]=p.screenY,t[A+3]=p.clientX,t[A+4]=p.clientY,t[A+5]=p.pageX,t[A+6]=p.pageY,t[A+7]=p.Td,t[A+8]=p.ie,t[A+9]=p.clientX-(va.left|0),t[A+10]=p.clientY-(va.top|0),A+=13,31<++m)break;t[w+8>>2]=m;W(d)(e,w,b)&&l.preventDefault()},Jd:c})},pc=[null,[],[]];
function qc(a,b,c,d,e,g){this.id=a;this.y=this.x=0;this.jd=!1;this.ke=this.je=0;this.width=b;this.height=c;this.Ad=d;this.zd=e;this.Gd=b;this.Fd=c;this.title=g;this.attributes=Object.assign({},X.Tc);this.Sd={208897:212993,208898:0,208899:0};this.buttons=0;this.keys=[];this.yd=[];this.title=null;this.ed=this.kd=this.hd=this.sd=this.fd=this.$c=this.od=this.ne=this.Od=this.oe=this.vd=this.wd=0}function rc(){const a=f.canvas;V(a,a.clientWidth,a.clientHeight);fc()}
function sc(){return X.active?0<X.active.attributes[139276]:!1}function tc(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1}
var X={Pc:a=>0>=a||!X.Qc?null:X.Qc[a-1],Yc:0,Ze:0,gf:0,active:null,scale:null,Qc:null,jf:null,hf:null,Kd:null,Rd:null,af:null,gd:null,Tc:null,bd:null,xe:{131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},pe:a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;
case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;
case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;
case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;
case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;
case 18:return 342;case 91:return 343;case 224:return 343;case 93:return 348;default:return-1}},Pd:a=>{var b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);if(a.keys[343]||a.keys[348])b|=8;return b},ce:a=>{X.active&&X.active.ed&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||W(X.active.ed)(X.active.id,a))},Dd:(a,b)=>{if(X.active){var c=X.pe(a);if(-1!=c){var d=b&&X.active.keys[c];X.active.keys[c]=b;X.active.yd[a]=b;X.active.kd&&(d&&(b=2),W(X.active.kd)(X.active.id,c,a,b,X.Pd(X.active)))}}},
ae:()=>{X.Ed()},be:()=>{X.Ed()},de:a=>{X.Dd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()},ee:a=>{X.Dd(a.keyCode,0)},Vd:()=>{if(X.active)for(var a=0;a<X.active.yd.length;++a)X.active.yd[a]&&X.Dd(a,0)},rd:a=>{if(X.active){if("touchmove"===a.type){a.preventDefault();let b=!1;for(let c of a.changedTouches)if(X.bd===c.identifier){bc(c.pageX,c.pageY);b=!0;break}if(!b)return}else cc(a);a.target==f.canvas&&X.active.$c&&X.active.$c&&W(X.active.$c)(X.active.id,Xb,Yb)}},qe:a=>{a=a.button;0<
a&&(a=1==a?2:1);return a},ge:a=>{X.active&&a.target==f.canvas&&X.active.fd&&W(X.active.fd)(X.active.id,1)},he:a=>{X.active&&a.target==f.canvas&&X.active.fd&&W(X.active.fd)(X.active.id,0)},fe:(a,b)=>{if(X.active&&a.target==f.canvas){var c=0;if("touchstart"===a.type||"touchend"===a.type||"touchcancel"===a.type){a.preventDefault();var d=!1;if(null===X.bd&&"touchstart"===a.type&&0<a.targetTouches.length)d=a.targetTouches[0],X.bd=d.identifier,bc(d.pageX,d.pageY),d=!0;else if("touchend"===a.type||"touchcancel"===
a.type)for(let e of a.changedTouches)if(X.bd===e.identifier){X.bd=null;d=!0;break}if(!d)return}else cc(a),c=X.qe(a);if(1==b){X.active.buttons|=1<<c;try{a.target.setCapture()}catch(e){}}else X.active.buttons&=~(1<<c);X.active.od&&W(X.active.od)(X.active.id,c,b,X.Pd(X.active))}},pd:a=>{X.active&&X.fe(a,1)},Zc:a=>{X.active&&X.fe(a,0)},qd:a=>{switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;
break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);X.Re+=b;if(X.active&&X.active.sd&&a.target==f.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;W(X.active.sd)(X.active.id,b,c);a.preventDefault()}},Wd:(a,b,c,d)=>{if(X.active){var e=!1;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?
X.active.jd||(e=a!=screen.width||b!=screen.height,X.active.je=X.active.x,X.active.ke=X.active.y,X.active.Gd=X.active.width,X.active.Fd=X.active.height,X.active.x=X.active.y=0,X.active.width=screen.width,X.active.height=screen.height,X.active.jd=!0):1==X.active.jd&&(e=a!=X.active.Gd||b!=X.active.Fd,X.active.x=X.active.je,X.active.y=X.active.ke,X.active.width=X.active.Gd,X.active.height=X.active.Fd,X.active.jd=!1);if(e)gc(X.active.width,X.active.height);else if(X.active.width!=a||X.active.height!=b||
X.active.Ad!=c||X.active.zd!=d)X.active.width=a,X.active.height=b,X.active.Ad=c,X.active.zd=d,X.Ge(),X.Ee()}},Ge:()=>{X.active&&X.active.wd&&W(X.active.wd)(X.active.id,X.active.width,X.active.height)},Ee:()=>{X.active&&X.active.Od&&W(X.active.Od)(X.active.id,X.active.Ad,X.active.zd)},Fe:a=>{X.scale=a;X.active&&X.active.ne&&W(X.active.ne)(X.active.id,X.scale,X.scale)},getTime:()=>ic()/1E3,Le:(a,b)=>{if(a=X.Pc(a))a.title=b,X.active.id==a.id&&(document.title=b?F(q,b):"")},sf:a=>{var b=X.Yc;X.Yc=a;X.Ed();
return b},Uc:{},Cd:[],Ud:null,Ed:()=>{if(Fb!==X.Ud||!Fb){X.Cd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads||[];X.Ud=Fb;for(var a=0;a<X.Cd.length;++a){var b=X.Cd[a];if(b){X.Uc[a]||(ea("glfw joystick connected:",a),X.Uc[a]={id:ob(b.id),Xe:b.buttons.length,We:b.axes.length,buttons:N(b.buttons.length),axes:N(4*b.axes.length)},X.Yc&&W(X.Yc)(a,262145));for(var c=X.Uc[a],d=0;d<b.buttons.length;++d)ja[c.buttons+d]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)z[c.axes+4*d>>
2]=b.axes[d]}else X.Uc[a]&&(ea("glfw joystick disconnected",a),X.Yc&&W(X.Yc)(a,262146),uc(X.Uc[a].id),uc(X.Uc[a].buttons),uc(X.Uc[a].axes),delete X.Uc[a])}}},He:(a,b)=>{a=X.Pc(a);if(!a)return null;var c=a.kd;a.kd=b;return c},mf:(a,b)=>{a=X.Pc(a);if(!a)return null;var c=a.ed;a.ed=b;return c},Ie:(a,b)=>{a=X.Pc(a);if(!a)return null;var c=a.od;a.od=b;return c},pf:(a,b)=>{a=X.Pc(a);if(!a)return null;var c=a.$c;a.$c=b;return c},Je:(a,b)=>{a=X.Pc(a);if(!a)return null;var c=a.sd;a.sd=b;return c},qf:(a,b)=>
{a=X.Pc(a);if(!a)return null;var c=a.hd;a.hd=b;return c},$d:a=>{if(X.active&&X.active.hd&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length)return a.preventDefault(),!1},Zd:a=>{if(X.active&&X.active.hd)return a.preventDefault(),!1},Ke:(a,b)=>{a=X.Pc(a);if(!a)return null;var c=a.wd;a.wd=b;return c},uf:(a,b)=>{a=X.Pc(a);if(!a)return null;var c=a.vd;a.vd=b;return c},wf:(a,b)=>{a=X.Pc(a);if(!a)return null;var c=a.oe;a.oe=b;return c},Xd:a=>{!Lb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),
a.preventDefault())},rf:(a,b,c)=>{if(a=X.Pc(a))switch(b){case 208897:switch(c){case 212993:a.Sd[b]=c;f.canvas.removeEventListener("click",X.Xd,!0);f.canvas.exitPointerLock();break;case 212994:k("glfwSetInputMode called with GLFW_CURSOR_HIDDEN value not implemented");break;case 212995:a.Sd[b]=c;f.canvas.addEventListener("click",X.Xd,!0);f.canvas.requestPointerLock();break;default:k(`glfwSetInputMode called with unknown value parameter value: ${c}`)}break;case 208898:k("glfwSetInputMode called with GLFW_STICKY_KEYS mode not implemented");
break;case 208899:k("glfwSetInputMode called with GLFW_STICKY_MOUSE_BUTTONS mode not implemented");break;case 208900:k("glfwSetInputMode called with GLFW_LOCK_KEY_MODS mode not implemented");break;case 3342341:k("glfwSetInputMode called with GLFW_RAW_MOUSE_MOTION mode not implemented");break;default:k(`glfwSetInputMode called with unknown mode parameter value: ${b}`)}},getKey:(a,b)=>(a=X.Pc(a))?a.keys[b]:0,cf:(a,b)=>(a=X.Pc(a))?0<(a.buttons&1<<b):0,Be:(a,b,c)=>{B[b>>3]=Xb;B[c>>3]=Yb},df:(a,b,c)=>
{t[b>>2]=Xb;t[c>>2]=Yb},nf:()=>{},ef:(a,b,c)=>{var d=0,e=0;if(a=X.Pc(a))d=a.x,e=a.y;b&&(t[b>>2]=d);c&&(t[c>>2]=e)},vf:(a,b,c)=>{if(a=X.Pc(a))a.x=b,a.y=c},ff:(a,b,c)=>{var d=0,e=0;if(a=X.Pc(a))d=a.width,e=a.height;b&&(t[b>>2]=d);c&&(t[c>>2]=e)},xf:(a,b,c)=>{(a=X.Pc(a))&&X.active.id==a.id&&gc(b,c)},ye:()=>{X.Tc=Object.assign({},X.xe)},ve:(a,b,c,d)=>{var e;for(e=0;e<X.Qc.length&&null!==X.Qc[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||0>=b)return 0;
d?Rb():gc(a,b);for(e=0;e<X.Qc.length&&null==X.Qc[e];e++);a=0<X.Tc[139265];e==X.Qc.length&&(a?f.Xc=Pb(f.canvas,!0,!0,{antialias:1<X.Tc[135181],depth:0<X.Tc[135173],stencil:0<X.Tc[135174],alpha:0<X.Tc[135172]}):Nb());if(!f.Xc&&a)return 0;e=f.canvas;c=new qc(g,e.clientWidth,e.clientHeight,e.width,e.height,c);g-1==X.Qc.length?X.Qc.push(c):X.Qc[g-1]=c;X.active=c;rc();return c.id},ze:a=>{if(a=X.Pc(a)){a.vd&&W(a.vd)(a.id);X.Qc[a.id-1]=null;X.active.id==a.id&&(X.active=null);for(a=0;a<X.Qc.length;a++)if(null!==
X.Qc[a])return;f.Xc=void 0}},yf:()=>{},requestFullscreen(a,b){function c(){R=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Sb,S&&d.requestPointerLock(),R=!0,U?Tb():(V(d),fc())):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),U?Ub():(V(d),fc()));if(f.onFullScreen)f.onFullScreen(R);if(f.onFullscreen)f.onFullscreen(R)}S=a;U=b;"undefined"==
typeof S&&(S=!0);"undefined"==typeof U&&(U=!1);var d=f.canvas;Qb||(Qb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):
null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()},Qe(a,b,c){var d=sc()?X.scale:1;b&&c?(a.Ld=b,a.Bd=c):(b=a.Ld,c=a.Bd);var e=b,g=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(e/g<f.forcedAspectRatio?e=Math.round(g*f.forcedAspectRatio):g=Math.round(e/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===
a.parentNode&&"undefined"!=typeof screen){var l=Math.min(screen.width/e,screen.height/g);e=Math.round(e*l);g=Math.round(g*l)}U&&(b=e,c=g);e=Math.floor(b*d);d=Math.floor(c*d);a.width!=e&&(a.width=e);a.height!=d&&(a.height=d);"undefined"!=typeof a.style&&(e!=b||d!=c?(a.style.setProperty("width",b+"px","important"),a.style.setProperty("height",c+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height")))},ue(a,b){var c=f.canvas.getBoundingClientRect(),d=f.canvas.clientHeight;
a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;a*=f.canvas.clientWidth/c.width;b*=d/c.height;return{x:a,y:b}},tf:(a,b,c)=>{if(a=X.Pc(a)){var d=sc();a.attributes[b]=c;d!==sc()&&rc()}},Yd(){X.Fe(tc());rc()},Se:a=>({196609:0,196610:0,196611:0,196612:0,196613:0,196614:0,131073:0,131074:0,131075:0,131076:0,131077:135169,131078:135170,131079:135171,131080:135172,131081:135173,131082:135174,
131083:135183,131084:135175,131085:135176,131086:135177,131087:135178,131088:135179,131089:135180,131090:0,131091:135181,131092:139266,131093:139267,131094:139270,131095:139271,131096:139272})[a]},vc=[31,29,31,30,31,30,31,31,30,31,30,31],wc=[31,28,31,30,31,30,31,31,30,31,30,31];function xc(a){var b=Array(nb(a)+1);D(a,b,0,b.length);return b}for(var L,Y=0;32>Y;++Y)ib.push(Array(Y));var yc=new Float32Array(288);for(Y=0;288>Y;++Y)P[Y]=yc.subarray(0,Y);var zc=new Int32Array(288);
for(Y=0;288>Y;++Y)vb[Y]=zc.subarray(0,Y);f.requestFullscreen=Rb;f.requestAnimationFrame=Wb;f.setCanvasSize=gc;f.pauseMainLoop=function(){Q=null;Ab++};f.resumeMainLoop=function(){Ab++;var a=Db,b=Eb,c=Bb;Bb=null;kc(c,0,!1,Cb,!0);jc(a,b);Q()};f.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};f.createContext=Pb;
var Ac={Qa:(a,b,c)=>q.copyWithin(a,b,b+c),Ma:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));t[c>>2]=a.getSeconds();t[c+4>>2]=a.getMinutes();t[c+8>>2]=a.getHours();t[c+12>>2]=a.getDate();t[c+16>>2]=a.getMonth();t[c+20>>2]=a.getFullYear()-1900;t[c+24>>2]=a.getDay();t[c+28>>2]=(Da(a.getFullYear())?Ea:Fa)[a.getMonth()]+a.getDate()-1|0;t[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
t[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},Oa:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=new Date(e,0,1),l=new Date(e,6,1);e=g.getTimezoneOffset();var p=l.getTimezoneOffset();v[a>>2]=60*Math.max(e,p);t[b>>2]=Number(e!=p);a=r=>r.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];g=a(g);l=a(l);p<e?(D(g,q,c,17),D(l,q,d,17)):(D(g,q,d,17),D(l,q,c,17))},Pa:()=>Date.now(),Hc:(a,b,c)=>{a=Qa(a);if(!a)return-4;a=0>Pa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};
B[b>>3]=a.width;B[c>>3]=a.height;return 0},sa:a=>{if(a){var b=document.pointerLockElement||document.dd||document.se||document.re;t[a>>2]=!!b;var c=b?.id||"";D(b?b==window?"#window":b==screen?"#screen":b?.nodeName||"":"",q,a+4,128);D(c,q,a+132,128)}return document.body&&(document.body.requestPointerLock||document.body.dd||document.body.se||document.body.re)?0:-1},ja:a=>L.activeTexture(a),ia:(a,b)=>{L.attachShader(G[a],J[b])},Aa:(a,b)=>{L.Sc.beginQueryEXT(a,K[b])},ha:(a,b,c)=>{L.bindAttribLocation(G[a],
b,c?F(q,c):"")},ga:(a,b)=>{L.bindBuffer(a,Wa[b])},fa:(a,b)=>{L.bindFramebuffer(a,Xa[b])},ea:(a,b)=>{L.bindRenderbuffer(a,H[b])},da:(a,b)=>{L.bindTexture(a,I[b])},ra:a=>{L.bindVertexArray(Ya[a])},ca:(a,b,c,d)=>L.blendColor(a,b,c,d),ba:a=>L.blendEquation(a),aa:(a,b)=>L.blendEquationSeparate(a,b),$:(a,b)=>L.blendFunc(a,b),_:(a,b,c,d)=>L.blendFuncSeparate(a,b,c,d),Y:(a,b,c,d)=>{L.bufferData(a,c?q.subarray(c,c+b):b,d)},X:(a,b,c,d)=>{L.bufferSubData(a,b,q.subarray(d,d+c))},W:a=>L.checkFramebufferStatus(a),
V:a=>L.clear(a),U:(a,b,c,d)=>L.clearColor(a,b,c,d),T:a=>L.clearDepth(a),S:a=>L.clearStencil(a),R:(a,b,c,d)=>{L.colorMask(!!a,!!b,!!c,!!d)},Q:a=>{L.compileShader(J[a])},P:(a,b,c,d,e,g,l,p)=>{L.compressedTexImage2D(a,b,c,d,e,g,p?q.subarray(p,p+l):null)},N:(a,b,c,d,e,g,l,p,r)=>{L.compressedTexSubImage2D(a,b,c,d,e,g,l,r?q.subarray(r,r+p):null)},M:(a,b,c,d,e,g,l,p)=>L.copyTexImage2D(a,b,c,d,e,g,l,p),L:(a,b,c,d,e,g,l,p)=>L.copyTexSubImage2D(a,b,c,d,e,g,l,p),K:()=>{var a=bb(G),b=L.createProgram();b.name=
a;b.nd=b.ld=b.md=0;b.Id=1;G[a]=b;return a},J:a=>{var b=bb(J);J[b]=L.createShader(a);return b},I:a=>L.cullFace(a),H:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Wa[d];e&&(L.deleteBuffer(e),e.name=0,Wa[d]=null)}},G:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=Xa[d];e&&(L.deleteFramebuffer(e),e.name=0,Xa[d]=null)}},F:a=>{if(a){var b=G[a];b?(L.deleteProgram(b),b.name=0,G[a]=null):M||=1281}},Ca:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=K[d];e&&(L.Sc.deleteQueryEXT(e),K[d]=null)}},E:(a,b)=>
{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=H[d];e&&(L.deleteRenderbuffer(e),e.name=0,H[d]=null)}},C:a=>{if(a){var b=J[a];b?(L.deleteShader(b),J[a]=null):M||=1281}},B:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=I[d];e&&(L.deleteTexture(e),e.name=0,I[d]=null)}},qa:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];L.deleteVertexArray(Ya[d]);Ya[d]=null}},A:a=>L.depthFunc(a),z:a=>{L.depthMask(!!a)},y:(a,b)=>L.depthRange(a,b),x:(a,b)=>{L.detachShader(G[a],J[b])},w:a=>L.disable(a),v:a=>{L.disableVertexAttribArray(a)},
u:(a,b,c)=>{L.drawArrays(a,b,c)},ma:(a,b,c,d)=>{L.drawArraysInstanced(a,b,c,d)},na:(a,b)=>{for(var c=ib[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];L.drawBuffers(c)},t:(a,b,c,d)=>{L.drawElements(a,b,c,d)},la:(a,b,c,d,e)=>{L.drawElementsInstanced(a,b,c,d,e)},r:a=>L.enable(a),q:a=>{L.enableVertexAttribArray(a)},za:a=>{L.Sc.endQueryEXT(a)},p:()=>L.finish(),o:()=>L.flush(),n:(a,b,c,d)=>{L.framebufferRenderbuffer(a,b,c,H[d])},m:(a,b,c,d,e)=>{L.framebufferTexture2D(a,b,c,I[d],e)},l:a=>L.frontFace(a),k:(a,b)=>{cb(a,
b,"createBuffer",Wa)},i:(a,b)=>{cb(a,b,"createFramebuffer",Xa)},Da:(a,b)=>{for(var c=0;c<a;c++){var d=L.Sc.createQueryEXT();if(!d){for(M||=1282;c<a;)t[b+4*c++>>2]=0;break}var e=bb(K);d.name=e;K[e]=d;t[b+4*c>>2]=e}},Gc:(a,b)=>{cb(a,b,"createRenderbuffer",H)},Fc:(a,b)=>{cb(a,b,"createTexture",I)},pa:(a,b)=>{cb(a,b,"createVertexArray",Ya)},j:a=>L.generateMipmap(a),Ec:(a,b,c,d,e,g,l)=>{jb("getActiveAttrib",a,b,c,d,e,g,l)},Dc:(a,b,c,d,e,g,l)=>{jb("getActiveUniform",a,b,c,d,e,g,l)},Cc:(a,b,c,d)=>{a=L.getAttachedShaders(G[a]);
var e=a.length;e>b&&(e=b);t[c>>2]=e;for(b=0;b<e;++b)t[d+4*b>>2]=J.indexOf(a[b])},Bc:(a,b)=>L.getAttribLocation(G[a],b?F(q,b):""),Ac:(a,b)=>kb(a,b,4),zc:(a,b,c)=>{c?t[c>>2]=L.getBufferParameter(a,b):M||=1281},yc:()=>{var a=L.getError()||M;M=0;return a},xc:(a,b)=>kb(a,b,2),wc:(a,b,c,d)=>{a=L.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;t[d>>2]=a},vc:(a,b)=>kb(a,b,0),tc:(a,b,c,d)=>{a=L.getProgramInfoLog(G[a]);null===a&&(a="(unknown error)");
b=0<b&&d?D(a,q,d,b):0;c&&(t[c>>2]=b)},uc:(a,b,c)=>{if(c)if(a>=Va)M||=1281;else if(a=G[a],35716==b)a=L.getProgramInfoLog(a),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.nd)for(b=0;b<L.getProgramParameter(a,35718);++b)a.nd=Math.max(a.nd,L.getActiveUniform(a,b).name.length+1);t[c>>2]=a.nd}else if(35722==b){if(!a.ld)for(b=0;b<L.getProgramParameter(a,35721);++b)a.ld=Math.max(a.ld,L.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.ld}else if(35381==b){if(!a.md)for(b=0;b<L.getProgramParameter(a,
35382);++b)a.md=Math.max(a.md,L.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.md}else t[c>>2]=L.getProgramParameter(a,b);else M||=1281},ua:lb,wa:mb,ta:lb,va:mb,xa:(a,b,c)=>{c?t[c>>2]=L.Sc.getQueryEXT(a,b):M||=1281},sc:(a,b,c)=>{c?t[c>>2]=L.getRenderbufferParameter(a,b):M||=1281},qc:(a,b,c,d)=>{a=L.getShaderInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,q,d,b):0;c&&(t[c>>2]=b)},pc:(a,b,c,d)=>{a=L.getShaderPrecisionFormat(a,b);t[c>>2]=a.rangeMin;t[c+4>>2]=a.rangeMax;t[d>>2]=a.precision},
oc:(a,b,c,d)=>{if(a=L.getShaderSource(J[a]))b=0<b&&d?D(a,q,d,b):0,c&&(t[c>>2]=b)},rc:(a,b,c)=>{c?35716==b?(a=L.getShaderInfoLog(J[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=L.getShaderSource(J[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=L.getShaderParameter(J[a],b):M||=1281},nc:a=>{var b=$a[a];if(!b){switch(a){case 7939:b=ob(pb().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=L.getParameter(a))||(M||=1280);b=b?ob(b):0;break;case 7938:b=ob(`OpenGL ES 2.0 (${L.getParameter(7938)})`);
break;case 35724:b=L.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=ob(b);break;default:M||=1280}$a[a]=b}return b},lc:(a,b,c)=>{c?z[c>>2]=L.getTexParameter(a,b):M||=1281},kc:(a,b,c)=>{c?t[c>>2]=L.getTexParameter(a,b):M||=1281},hc:(a,b)=>{b=b?F(q,b):"";if(a=G[a]){rb(a);var c=a.cd,d=0,e=b,g=qb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.me[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||
L.getUniformLocation(a,b)))return d}else M||=1281;return-1},jc:(a,b,c)=>{sb(a,b,c,2)},ic:(a,b,c)=>{sb(a,b,c,0)},ec:(a,b,c)=>{c?t[c>>2]=L.getVertexAttribOffset(a,b):M||=1281},gc:(a,b,c)=>{tb(a,b,c,2)},fc:(a,b,c)=>{tb(a,b,c,5)},dc:(a,b)=>L.hint(a,b),cc:a=>(a=Wa[a])?L.isBuffer(a):0,ac:a=>L.isEnabled(a),$b:a=>(a=Xa[a])?L.isFramebuffer(a):0,_b:a=>(a=G[a])?L.isProgram(a):0,Ba:a=>(a=K[a])?L.Sc.isQueryEXT(a):0,Zb:a=>(a=H[a])?L.isRenderbuffer(a):0,Yb:a=>(a=J[a])?L.isShader(a):0,Xb:a=>(a=I[a])?L.isTexture(a):
0,oa:a=>(a=Ya[a])?L.isVertexArray(a):0,Wb:a=>L.lineWidth(a),Vb:a=>{a=G[a];L.linkProgram(a);a.cd=0;a.me={}},Ub:(a,b)=>{3317==a&&(ab=b);L.pixelStorei(a,b)},Tb:(a,b)=>L.polygonOffset(a,b),ya:(a,b)=>{L.Sc.queryCounterEXT(K[a],b)},Rb:(a,b,c,d,e,g,l)=>{(l=ub(g,e,c,d,l))?L.readPixels(a,b,c,d,e,g,l):M||=1280},Qb:()=>{},Pb:(a,b,c,d)=>L.renderbufferStorage(a,b,c,d),Ob:(a,b)=>{L.sampleCoverage(a,!!b)},Nb:(a,b,c,d)=>L.scissor(a,b,c,d),Mb:()=>{M||=1280},Lb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var l=(l=v[c+4*
g>>2])?F(q,l,d?v[d+4*g>>2]:void 0):"";e+=l}L.shaderSource(J[a],e)},Kb:(a,b,c)=>L.stencilFunc(a,b,c),Jb:(a,b,c,d)=>L.stencilFuncSeparate(a,b,c,d),Ib:a=>L.stencilMask(a),Gb:(a,b)=>L.stencilMaskSeparate(a,b),Fb:(a,b,c)=>L.stencilOp(a,b,c),Eb:(a,b,c,d)=>L.stencilOpSeparate(a,b,c,d),Db:(a,b,c,d,e,g,l,p,r)=>{r=r?ub(p,l,d,e,r):null;L.texImage2D(a,b,c,d,e,g,l,p,r)},Cb:(a,b,c)=>L.texParameterf(a,b,c),Bb:(a,b,c)=>{L.texParameterf(a,b,z[c>>2])},Ab:(a,b,c)=>L.texParameteri(a,b,c),zb:(a,b,c)=>{L.texParameteri(a,
b,t[c>>2])},yb:(a,b,c,d,e,g,l,p,r)=>{r=r?ub(p,l,e,g,r):null;L.texSubImage2D(a,b,c,d,e,g,l,p,r)},xb:(a,b)=>{L.uniform1f(O(a),b)},vb:(a,b,c)=>{if(288>=b)for(var d=P[b],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);L.uniform1fv(O(a),d)},ub:(a,b)=>{L.uniform1i(O(a),b)},tb:(a,b,c)=>{if(288>=b)for(var d=vb[b],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);L.uniform1iv(O(a),d)},sb:(a,b,c)=>{L.uniform2f(O(a),b,c)},rb:(a,b,c)=>{if(144>=b)for(var d=P[2*b],e=0;e<2*b;e+=2)d[e]=
z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);L.uniform2fv(O(a),d)},qb:(a,b,c)=>{L.uniform2i(O(a),b,c)},pb:(a,b,c)=>{if(144>=b)for(var d=vb[2*b],e=0;e<2*b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2];else d=t.subarray(c>>2,c+8*b>>2);L.uniform2iv(O(a),d)},ob:(a,b,c,d)=>{L.uniform3f(O(a),b,c,d)},nb:(a,b,c)=>{if(96>=b)for(var d=P[3*b],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);L.uniform3fv(O(a),d)},mb:(a,b,c,d)=>
{L.uniform3i(O(a),b,c,d)},kb:(a,b,c)=>{if(96>=b)for(var d=vb[3*b],e=0;e<3*b;e+=3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2];else d=t.subarray(c>>2,c+12*b>>2);L.uniform3iv(O(a),d)},jb:(a,b,c,d,e)=>{L.uniform4f(O(a),b,c,d,e)},ib:(a,b,c)=>{if(72>=b){var d=P[4*b],e=z;c>>=2;for(var g=0;g<4*b;g+=4){var l=c+g;d[g]=e[l];d[g+1]=e[l+1];d[g+2]=e[l+2];d[g+3]=e[l+3]}}else d=z.subarray(c>>2,c+16*b>>2);L.uniform4fv(O(a),d)},hb:(a,b,c,d,e)=>{L.uniform4i(O(a),b,c,d,e)},gb:(a,b,c)=>{if(72>=b)for(var d=
vb[4*b],e=0;e<4*b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2];else d=t.subarray(c>>2,c+16*b>>2);L.uniform4iv(O(a),d)},fb:(a,b,c,d)=>{if(72>=b)for(var e=P[4*b],g=0;g<4*b;g+=4)e[g]=z[d+4*g>>2],e[g+1]=z[d+(4*g+4)>>2],e[g+2]=z[d+(4*g+8)>>2],e[g+3]=z[d+(4*g+12)>>2];else e=z.subarray(d>>2,d+16*b>>2);L.uniformMatrix2fv(O(a),!!c,e)},eb:(a,b,c,d)=>{if(32>=b)for(var e=P[9*b],g=0;g<9*b;g+=9)e[g]=z[d+4*g>>2],e[g+1]=z[d+(4*g+4)>>2],e[g+2]=z[d+(4*g+8)>>2],e[g+3]=
z[d+(4*g+12)>>2],e[g+4]=z[d+(4*g+16)>>2],e[g+5]=z[d+(4*g+20)>>2],e[g+6]=z[d+(4*g+24)>>2],e[g+7]=z[d+(4*g+28)>>2],e[g+8]=z[d+(4*g+32)>>2];else e=z.subarray(d>>2,d+36*b>>2);L.uniformMatrix3fv(O(a),!!c,e)},db:(a,b,c,d)=>{if(18>=b){var e=P[16*b],g=z;d>>=2;for(var l=0;l<16*b;l+=16){var p=d+l;e[l]=g[p];e[l+1]=g[p+1];e[l+2]=g[p+2];e[l+3]=g[p+3];e[l+4]=g[p+4];e[l+5]=g[p+5];e[l+6]=g[p+6];e[l+7]=g[p+7];e[l+8]=g[p+8];e[l+9]=g[p+9];e[l+10]=g[p+10];e[l+11]=g[p+11];e[l+12]=g[p+12];e[l+13]=g[p+13];e[l+14]=g[p+14];
e[l+15]=g[p+15]}}else e=z.subarray(d>>2,d+64*b>>2);L.uniformMatrix4fv(O(a),!!c,e)},cb:a=>{a=G[a];L.useProgram(a);L.we=a},bb:a=>{L.validateProgram(G[a])},$a:(a,b)=>L.vertexAttrib1f(a,b),_a:(a,b)=>{L.vertexAttrib1f(a,z[b>>2])},Za:(a,b,c)=>L.vertexAttrib2f(a,b,c),Ya:(a,b)=>{L.vertexAttrib2f(a,z[b>>2],z[b+4>>2])},Xa:(a,b,c,d)=>L.vertexAttrib3f(a,b,c,d),Wa:(a,b)=>{L.vertexAttrib3f(a,z[b>>2],z[b+4>>2],z[b+8>>2])},Va:(a,b,c,d,e)=>L.vertexAttrib4f(a,b,c,d,e),Ua:(a,b)=>{L.vertexAttrib4f(a,z[b>>2],z[b+4>>2],
z[b+8>>2],z[b+12>>2])},ka:(a,b)=>{L.vertexAttribDivisor(a,b)},Ta:(a,b,c,d,e,g)=>{L.vertexAttribPointer(a,b,c,!!d,e,g)},Sa:(a,b,c,d)=>L.viewport(a,b,c,d),Na:()=>{sa("OOM")},O:(a,b,c)=>{a=Qa(a);if(!a)return-4;a.width=b;a.height=c;return 0},Fa:(a,b,c)=>{a=W(a);kc(a,b,c)},Ga:(a,b,c,d)=>nc(a,b,c,d),Ha:(a,b,c,d)=>oc(a,b,c,d,24,"touchmove"),Ia:(a,b,c,d)=>oc(a,b,c,d,22,"touchstart"),a:yb,f:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var l=v[b>>2],p=v[b+4>>2];b+=8;for(var r=0;r<p;r++){var w=q[l+r],u=pc[a];0===w||
10===w?((1===a?ea:k)(F(u,0)),u.length=0):u.push(w)}e+=p}v[d>>2]=e;return 0},mc:(a,b,c,d,e)=>X.ve(a,b,c,d,e),Ea:a=>X.ze(a),c:(a,b,c)=>X.Be(a,b,c),bc:()=>1,d:()=>X.getTime()-X.Rd,D:()=>{X.Kd||(X.Kd=ob("3.2.1 JS WebGL Emscripten"));return X.Kd},Sb:()=>0,s:()=>{if(X.Qc)return 1;X.Rd=X.getTime();X.ye();X.Qc=[];X.active=null;X.scale=tc();window.addEventListener("gamepadconnected",X.ae,!0);window.addEventListener("gamepaddisconnected",X.be,!0);window.addEventListener("keydown",X.de,!0);window.addEventListener("keypress",
X.ce,!0);window.addEventListener("keyup",X.ee,!0);window.addEventListener("blur",X.Vd,!0);X.gd=window.matchMedia("(resolution: "+tc()+"dppx)");X.gd.addEventListener("change",X.Yd);f.canvas.addEventListener("touchmove",X.rd,!0);f.canvas.addEventListener("touchstart",X.pd,!0);f.canvas.addEventListener("touchcancel",X.Zc,!0);f.canvas.addEventListener("touchend",X.Zc,!0);f.canvas.addEventListener("mousemove",X.rd,!0);f.canvas.addEventListener("mousedown",X.pd,!0);f.canvas.addEventListener("mouseup",X.Zc,
!0);f.canvas.addEventListener("wheel",X.qd,!0);f.canvas.addEventListener("mousewheel",X.qd,!0);f.canvas.addEventListener("mouseenter",X.ge,!0);f.canvas.addEventListener("mouseleave",X.he,!0);f.canvas.addEventListener("drop",X.$d,!0);f.canvas.addEventListener("dragover",X.Zd,!0);Rb=X.requestFullscreen;ac=X.ue;V=X.Qe;dc.push((a,b)=>{if(sc()){var c=f.canvas;X.Wd(c.clientWidth,c.clientHeight,a,b)}else X.Wd(a,b,a,b)});return 1},Ra:()=>{},La:()=>{},wb:(a,b)=>X.He(a,b),lb:(a,b)=>X.Ie(a,b),ab:(a,b)=>X.Je(a,
b),Ja:()=>{},Hb:(a,b)=>X.Ke(a,b),g:(a,b)=>X.Le(a,b),Z:()=>{},Ka:a=>{a=Math.abs(a);0==a?jc(0,0):jc(1,a)},e:()=>{window.removeEventListener("gamepadconnected",X.ae,!0);window.removeEventListener("gamepaddisconnected",X.be,!0);window.removeEventListener("keydown",X.de,!0);window.removeEventListener("keypress",X.ce,!0);window.removeEventListener("keyup",X.ee,!0);window.removeEventListener("blur",X.Vd,!0);f.canvas.removeEventListener("touchmove",X.rd,!0);f.canvas.removeEventListener("touchstart",X.pd,
!0);f.canvas.removeEventListener("touchcancel",X.Zc,!0);f.canvas.removeEventListener("touchend",X.Zc,!0);f.canvas.removeEventListener("mousemove",X.rd,!0);f.canvas.removeEventListener("mousedown",X.pd,!0);f.canvas.removeEventListener("mouseup",X.Zc,!0);f.canvas.removeEventListener("wheel",X.qd,!0);f.canvas.removeEventListener("mousewheel",X.qd,!0);f.canvas.removeEventListener("mouseenter",X.ge,!0);f.canvas.removeEventListener("mouseleave",X.he,!0);f.canvas.removeEventListener("drop",X.$d,!0);f.canvas.removeEventListener("dragover",
X.Zd,!0);X.gd&&X.gd.removeEventListener("change",X.Yd);f.canvas.width=f.canvas.height=1;X.Qc=null;X.active=null},b:(a,b)=>{X.Tc[a]=b},h:(a,b,c,d)=>{function e(m,x,y){for(m="number"==typeof m?m.toString():m||"";m.length<x;)m=y[0]+m;return m}function g(m,x){return e(m,x,"0")}function l(m,x){function y(ec){return 0>ec?-1:0<ec?1:0}var T;0===(T=y(m.getFullYear()-x.getFullYear()))&&0===(T=y(m.getMonth()-x.getMonth()))&&(T=y(m.getDate()-x.getDate()));return T}function p(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-
1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),0,2);case 4:return new Date(m.getFullYear(),0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function r(m){var x=m.Vc;for(m=new Date((new Date(m.Wc+1900,0,1)).getTime());0<x;){var y=m.getMonth(),T=(Da(m.getFullYear())?vc:wc)[y];if(x>T-m.getDate())x-=T-m.getDate()+1,m.setDate(1),11>y?m.setMonth(y+1):(m.setMonth(0),m.setFullYear(m.getFullYear()+
1));else{m.setDate(m.getDate()+x);break}}y=new Date(m.getFullYear()+1,0,4);x=p(new Date(m.getFullYear(),0,4));y=p(y);return 0>=l(x,m)?0>=l(y,m)?m.getFullYear()+1:m.getFullYear():m.getFullYear()-1}var w=v[d+40>>2];d={Oe:t[d>>2],Ne:t[d+4>>2],td:t[d+8>>2],Hd:t[d+12>>2],ud:t[d+16>>2],Wc:t[d+20>>2],Rc:t[d+24>>2],Vc:t[d+28>>2],Af:t[d+32>>2],Me:t[d+36>>2],Pe:w?w?F(q,w):"":""};c=c?F(q,c):"";w={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in w)c=c.replace(new RegExp(u,"g"),w[u]);var A="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),va="January February March April May June July August September October November December".split(" ");w={"%a":m=>A[m.Rc].substring(0,
3),"%A":m=>A[m.Rc],"%b":m=>va[m.ud].substring(0,3),"%B":m=>va[m.ud],"%C":m=>g((m.Wc+1900)/100|0,2),"%d":m=>g(m.Hd,2),"%e":m=>e(m.Hd,2," "),"%g":m=>r(m).toString().substring(2),"%G":r,"%H":m=>g(m.td,2),"%I":m=>{m=m.td;0==m?m=12:12<m&&(m-=12);return g(m,2)},"%j":m=>{for(var x=0,y=0;y<=m.ud-1;x+=(Da(m.Wc+1900)?vc:wc)[y++]);return g(m.Hd+x,3)},"%m":m=>g(m.ud+1,2),"%M":m=>g(m.Ne,2),"%n":()=>"\n","%p":m=>0<=m.td&&12>m.td?"AM":"PM","%S":m=>g(m.Oe,2),"%t":()=>"\t","%u":m=>m.Rc||7,"%U":m=>g(Math.floor((m.Vc+
7-m.Rc)/7),2),"%V":m=>{var x=Math.floor((m.Vc+7-(m.Rc+6)%7)/7);2>=(m.Rc+371-m.Vc-2)%7&&x++;if(x)53==x&&(y=(m.Rc+371-m.Vc)%7,4==y||3==y&&Da(m.Wc)||(x=1));else{x=52;var y=(m.Rc+7-m.Vc-1)%7;(4==y||5==y&&Da(m.Wc%400-1))&&x++}return g(x,2)},"%w":m=>m.Rc,"%W":m=>g(Math.floor((m.Vc+7-(m.Rc+6)%7)/7),2),"%y":m=>(m.Wc+1900).toString().substring(2),"%Y":m=>m.Wc+1900,"%z":m=>{m=m.Me;var x=0<=m;m=Math.abs(m)/60;return(x?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":m=>m.Pe,"%%":()=>"%"};c=c.replace(/%%/g,
"\x00\x00");for(u in w)c.includes(u)&&(c=c.replace(new RegExp(u,"g"),w[u](d)));c=c.replace(/\0\0/g,"%");u=xc(c);if(u.length>b)return 0;ja.set(u,a);return u.length-1}},Z=function(){function a(c){Z=c.exports;ha=Z.Ic;c=ha.buffer;f.HEAP8=ja=new Int8Array(c);f.HEAP16=new Int16Array(c);f.HEAPU8=q=new Uint8Array(c);f.HEAPU16=ka=new Uint16Array(c);f.HEAP32=t=new Int32Array(c);f.HEAPU32=v=new Uint32Array(c);f.HEAPF32=z=new Float32Array(c);f.HEAPF64=B=new Float64Array(c);mc=Z.Nc;ma.unshift(Z.Jc);C--;f.monitorRunDependencies?.(C);
0==C&&(null!==qa&&(clearInterval(qa),qa=null),ra&&(c=ra,ra=null,c()));return Z}var b={a:Ac};C++;f.monitorRunDependencies?.(C);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return k(`Module.instantiateWasm callback failed with error: ${c}`),!1}ua||=ta("index.wasm")?"index.wasm":f.locateFile?f.locateFile("index.wasm",h):h+"index.wasm";za(b,function(c){a(c.instance)});return{}}(),N=a=>(N=Z.Kc)(a),uc=a=>(uc=Z.Lc)(a),Bc=f._main=(a,b)=>(Bc=f._main=Z.Mc)(a,b),Cc=a=>(Cc=Z.Oc)(a),Dc;
ra=function Ec(){Dc||Fc();Dc||(ra=Ec)};function Gc(a=[]){var b=Bc;a.unshift(ca);var c=a.length,d=Cc(4*(c+1)),e=d;a.forEach(l=>{var p=v,r=e>>2,w=nb(l)+1,u=Cc(w);D(l,q,u,w);p[r]=u;e+=4});v[e>>2]=0;try{var g=b(c,d);yb(g,!0)}catch(l){wb(l)}}
function Fc(){var a=ba;function b(){if(!Dc&&(Dc=!0,f.calledRun=!0,!n)){Ba(ma);Ba(na);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Hc&&Gc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();oa.unshift(c)}Ba(oa)}}if(!(0<C)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)pa();Ba(la);0<C||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},
1)):b())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Hc=!0;f.noInitialRun&&(Hc=!1);Fc();
